# Generated by Django 4.2.27 on 2026-03-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='jober',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to=settings.AUTH_USER_MODEL),
        ),
    ]
