# Generated by Django 4.2.27 on 2026-05-04 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_machinemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinemaster',
            name='id',
        ),
        migrations.AddField(
            model_name='machinemaster',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
