# Generated by Django 4.2.27 on 2026-05-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_currencymaster_machinemaster_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machine_images/'),
        ),
    ]
