# Generated by Django 4.2.27 on 2026-05-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_production_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemaster',
            name='jober_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='production',
            name='jober_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
