# Generated by Django 4.2.27 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reset_otp_user_reset_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
